# Site settings
title: Aaron Nunley
email: aaron@rocketsociety.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll default build.  To-do:  Everything.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aaron.rocketsociety.com" # the base hostname & protocol for your site
twitter_username: rocketsocietyan
github_username:  aaron-nunley

# Build settings
markdown: kramdown
