# Site settings
title: Aaron Nunley
email: aaron@rocketsociety.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll default build.  To-do:  Everything.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aaron.rocketsociety.com" # the base hostname & protocol for your site
permalink: /blog/:year/:title
exclude: [vendor]
markdown: kramdown

sass:
    style: :compressed

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap